// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcsmsxpldtlpgkgkusgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjc21zeHBsZHRscGdrZ2t1c2dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0OTc3NjcsImV4cCI6MjA3MDA3Mzc2N30.frHa4NBYC5MQRfZIzWt5BI1kKQDcbg_ztKHmcv52oOM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});